services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount the current directory to /app for development (hot-reloading)
      # The Dockerfile's `COPY . /app/` will be used for the initial build.
      - .:/app
      # Named volumes for persistent data
      - uploaded_files_data:/app/uploaded_files
      - output_data:/app/output
    env_file:
      # Load environment variables from .env file in the project root
      - ./.env
    # The command from the Dockerfile (CMD) will be used by default:
    # CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  uploaded_files_data:
  output_data:
